// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nexus-designs/AuroraGradient.tsx": () => import("../components/mockups/nexus-designs/AuroraGradient.tsx"),
  "./components/mockups/nexus-designs/Brutalist.tsx": () => import("../components/mockups/nexus-designs/Brutalist.tsx"),
  "./components/mockups/nexus-designs/MinimalMono.tsx": () => import("../components/mockups/nexus-designs/MinimalMono.tsx"),
  "./components/mockups/nexus-designs/NeonCyber.tsx": () => import("../components/mockups/nexus-designs/NeonCyber.tsx"),
  "./components/mockups/nexus-ux/FeedScreen.tsx": () => import("../components/mockups/nexus-ux/FeedScreen.tsx"),
  "./components/mockups/nexus-ux/OnboardingScreen.tsx": () => import("../components/mockups/nexus-ux/OnboardingScreen.tsx"),
  "./components/mockups/nexus-ux/SpacesScreen.tsx": () => import("../components/mockups/nexus-ux/SpacesScreen.tsx"),
  "./components/mockups/nexus-ux/StreakScreen.tsx": () => import("../components/mockups/nexus-ux/StreakScreen.tsx")
};
